name: Spiritual
favicon: null
layout_spectrum: 0.21991520142182708
typography_spectrum: 0.5865018027834594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9349091341719031
  lightness: 0.7009709293488413
  saturation: 0.8708177926018834
  rhythmicContrast: 0.393887001555413
purpose: []
